name: GesisLearning-environment
channels:
  - conda-forge
  - anaconda
dependencies:
  - python=3.7.3
  - numpy=1.16.4
  - seaborn
  - rise
  - pip
  - pip:
    - julia
  - scijava-jupyter-kernel
  - xeus-cling=0.8.1
